--- 
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata: 
  name: collector-sample
spec:
  collectors:
    - http: 
        collectorName: fortunecookie
        get: 
          url: "https://quotes.rest/qod"
