--- 
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata: 
  name: collector-sample
spec: 
  collectors:
    - logs: 
        limits: 
          maxAge: 30d
          maxLines: 10000
        namespace: kube-system
        selector: 
          - component=kube-controller-manager
          - tier=control-plane
