apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
    - run:
        collectorName: netstat
        namespace: default
        image: flungo/netutils
        command: ["netstat"]
        args: ["-n","-a"]
        timeout: 5s
