apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  - secret:
      name: app.yaml
      namespace: default
      key: ca.crt
      includeValue: true
  - secret:
      name: app.yaml
      namespace: default
      key: token
      includeValue: false      
