apiVersion: troubleshoot.replicated.com/v1beta1
kind: Collector
metadata:
  name: collector-sample
spec:
  collectors:
    - secret:
      name: flux-token-g8scp
      namespace: default
      key: ca.crt
      includeValue: true
    - secret:
      name: flux-token-g8scp
      namespace: default
      key: token
      includeValue: false
      
